'use client'

import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function TermsPage() {
  const Navigation = () => {
    const pathname = usePathname();
    return (
      <nav className="support-nav" style={{ position: "fixed", display: "flex", gap: "0.5rem"}}>
        <Link href="/" className="support-link">Home</Link>
        <Link href="/apps" className="support-link">Our Apps</Link>
        <Link href="/support" className="support-link">Support</Link>
        <Link href="/privacy" className="support-link">Privacy</Link>
      </nav>
    );
  };

  return (
    <div className="App">
      <Navigation />
      <div style={{ 
        maxWidth: "800px", 
        margin: "0 auto", 
        padding: "6rem 2rem 2rem 2rem", 
        color: "#ededed",
        lineHeight: "1.6"
      }}>
        <h1 style={{ 
          color: "#33F0CE", 
          fontSize: "2.5rem", 
          marginBottom: "2rem",
          textAlign: "center"
        }}>
          Terms of Service
        </h1>
        
        <div style={{ 
          backgroundColor: "#111", 
          padding: "1.5rem", 
          borderRadius: "8px",
          border: "1px solid #333",
          marginBottom: "2rem"
        }}>
          <p style={{ marginBottom: "1rem", fontSize: "0.9rem", color: "#ccc" }}>
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
          <p style={{ marginBottom: "1rem" }}>
            Please read these Terms of Service ("Terms") carefully before using any mobile application published by BitLion, LLC ("us", "we", or "our"). These Terms apply to all of our apps, including Budget Plant ID and SlowPulse (each, an "App").
          </p>
          <p style={{ marginBottom: "1rem" }}>
            By accessing or using an App, you agree to be bound by these Terms. If you disagree with any part of these Terms, then you may not use the App.
          </p>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            1. Acceptance of Terms
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              By downloading, installing, or using one of our Apps, you acknowledge that you have read, understood, and agree to be bound by these Terms and our <Link href="/privacy" style={{ color: "#33F0CE" }}>Privacy Policy</Link>.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            2. Description of Service
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              We build consumer mobile applications for iOS and Android. Each App&apos;s specific functionality is described on its app store listing and on our <Link href="/apps" style={{ color: "#33F0CE" }}>Our Apps</Link> page.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Budget Plant ID</strong> lets you photograph a plant and receive an identification and plant health information generated by a third-party image recognition service.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>SlowPulse</strong> helps you interrupt impulsive phone use by showing a pause screen before you open apps you have chosen to guard, and by keeping a record of those moments so you can review your own patterns.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              We may add, change, or discontinue features of any App at any time.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            3. No Professional Advice
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              Our Apps are provided for general informational and personal use only. They do not provide professional advice of any kind, and you should not rely on them as a substitute for it.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Plant identification results are not authoritative.</strong> Identifications, plant health diagnoses, toxicity information, and treatment suggestions are automated estimates and may be incomplete or wrong. Never eat, handle, apply, or administer any plant or treatment based on an App&apos;s output. Consult a qualified professional, and in a suspected poisoning contact emergency services or a poison control center immediately.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>SlowPulse is not a medical or financial service.</strong> It is a self-management tool, not treatment for compulsive spending, addiction, or any other condition, and its statistics are not financial advice. If you are struggling, please seek help from a qualified professional.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            4. User Accounts
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Optional Accounts:</strong> Most of our Apps work without an account. Where an App offers optional sign-in for backup or syncing between devices, you are responsible for maintaining the confidentiality of your account credentials.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Account Security:</strong> You agree to notify us immediately of any unauthorized use of your account or any other breach of security. We are not liable for any loss or damage arising from your failure to protect your account information.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Account Termination:</strong> We reserve the right to suspend or terminate your account at any time for violations of these Terms or for any other reason we deem necessary.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            5. Your Content and Conduct
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Your Content:</strong> You retain ownership of any content you provide to an App, such as photos you take or select and notes you write. By using an App, you grant us a limited license to process, store, and transmit that content solely for the purpose of providing the features you requested — for example, sending a photo to our identification provider so it can be identified.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Your Responsibility:</strong> You represent that you have the right to submit any content you provide, and you agree not to submit content that:
            </p>
            <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
              <li>Violates any laws or regulations</li>
              <li>Infringes on intellectual property or privacy rights of others</li>
              <li>Is pornographic, obscene, or sexually explicit</li>
              <li>Contains malware, viruses, or harmful code</li>
            </ul>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Acceptable Use:</strong> You agree not to reverse engineer, decompile, or tamper with an App, to circumvent its purchase or credit systems, to use it to harass or surveil another person, or to access it through automated means or in a way that places an unreasonable load on our services or those of our providers.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            6. Device Permissions and Third-Party Services
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Permissions:</strong> Some features require device permissions — for example, camera and photo library access for plant identification, or notification and app-guarding permissions for SlowPulse. You grant these permissions yourself and may revoke them at any time in your device settings. Revoking a permission may disable the features that depend on it.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>App Guarding Is Best-Effort:</strong> SlowPulse relies on operating system features provided by Apple and Google to show its pause screen. We do not guarantee that every launch of a guarded app will be intercepted. Operating system updates, battery optimization, permission changes, and device restarts can all interrupt guarding, and SlowPulse is not a security or parental control product.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Third-Party Services:</strong> Our Apps depend on services we do not control, including image recognition, authentication, sync, and purchase providers, as well as the Apple App Store and Google Play. Those providers may change, restrict, or discontinue their services at any time, which may affect an App&apos;s functionality. We are not responsible for disruptions caused by them, and your use of an App is also subject to the terms of the app store you obtained it from.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            7. Intellectual Property
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              Our Apps, including their original content, features, and functionality, are owned by BitLion, LLC and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              You may not copy, modify, distribute, sell, or lease any part of our Apps without our express written permission.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            8. Payment, Credits, and Subscriptions
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Fees:</strong> Some features require payment. All purchases are processed by the Apple App Store or Google Play and are subject to their terms and refund policies. All fees are non-refundable unless required by law or as otherwise stated.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Credits:</strong> Where an App sells credits or another consumable, those credits have no cash value, are not transferable or redeemable for money, and are usable only within that App. Credits are stored on your device, so uninstalling the App or resetting your device may cause any unused credits to be lost.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Subscriptions:</strong> If you purchase a subscription, it will automatically renew at the then-current price unless you cancel at least 24 hours before the end of the current period. You may cancel at any time through your app store account settings; cancellation takes effect at the end of the current period.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Price Changes:</strong> We reserve the right to change our pricing at any time. Price changes will not affect your current subscription period but will apply to renewals.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            9. Disclaimer of Warranties
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              THE APPS ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              We do not warrant that any result produced by an App — including any plant identification or diagnosis — is accurate, complete, or reliable. We do not guarantee that an App will be uninterrupted, secure, or error-free, or that defects will be corrected.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              <strong>Your Data:</strong> Most data our Apps create is stored on your device. You are responsible for maintaining your own backups. We are not liable for data lost through device failure, uninstallation, or a sync interruption.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            10. Limitation of Liability
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, BITLION, LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE APPS.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              Our total liability for any claims arising from or related to an App shall not exceed the amount you paid us in the twelve (12) months preceding the claim.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              Some jurisdictions do not allow the exclusion of certain warranties or the limitation of certain damages, so some of the above may not apply to you.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            11. Indemnification
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              You agree to indemnify, defend, and hold harmless BitLion, LLC and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including attorneys&apos; fees) arising out of or relating to your use of an App, your content, or your violation of these Terms.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            12. Termination
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              We may terminate or suspend your access to an App immediately, without prior notice, for any reason, including if you breach these Terms. You may end these Terms at any time by uninstalling the App.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              Upon termination, your right to use the App will cease immediately. All provisions of these Terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, and limitations of liability.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            13. Changes to Terms
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days&apos; notice prior to any new terms taking effect.
            </p>
            <p style={{ marginBottom: "1rem" }}>
              Your continued use of an App after any changes constitutes acceptance of the new Terms.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            14. Governing Law
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which BitLion, LLC operates, without regard to its conflict of law provisions.
            </p>
          </div>
        </div>

        <div style={{ marginBottom: "2rem" }}>
          <h2 style={{ 
            color: "#33F0CE", 
            fontSize: "1.8rem", 
            marginBottom: "1rem"
          }}>
            15. Contact Information
          </h2>
          <div style={{ 
            backgroundColor: "#111", 
            padding: "1.5rem", 
            borderRadius: "8px",
            border: "1px solid #333"
          }}>
            <p style={{ marginBottom: "1rem" }}>
              If you have any questions about these Terms of Service, please contact us at{' '}
              <a href="mailto:grant@thebitlion.com" style={{ color: "#33F0CE" }}>grant@thebitlion.com</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
